highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://andreavaghi.github.io/resume
author: Andrea Vaghi

baseurl: /resume/
title: Andrea Vaghi's Resume
name: Andrea Vaghi
email: andreavaghi@gmail.com
email_full: mailto:andreavaghi@gmail.com
website: andreavaghi.com
website_full: http://www.andreavaghi.com
github: andreavaghi
twitter: andreavaghi
tel: +39 328 9392071
tel_full: tel:+393289392071
google_maps: ''
address: Via Campagna, 59
postcode: 26865
city: San Rocco al Porto
country: Italy
google_analytics: UA-18436516-1

# needed for travis-ci build
exclude: [vendor]
